# Custom Aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias lst='ls -tr1'
alias lll='ls -haotr'

alias naut='nautilus . &'
alias tree2='tree -L 2'
alias tree3='tree -L 3'
alias rdl='readlink -f'
alias vsc='code'
alias temps='watch -n 0.2 sensors'
alias psall='top -c'
alias duu='du -h --max-depth=1'
alias tmuxKill='tmux kill-server'
alias tmuxAttach='tmux attach'
alias ipp='ipython --colors linux --no-confirm-exit --no-banner'
alias pdb='python $'
