# On fresh install run or copy `runtime` folder
# from source to .config/helix/
# hx --grammar fetch
# hx --grammar build 

[[language]]
name = "python"
language-servers = [ "ruff", "ty" ]
auto-format = true

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.ty]
command = "ty"
args = ["server"]

